server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  server:
    enable-self-preservation: true
    expected-client-renewal-interval-seconds: 100
    eviction-interval-timer-in-ms: 600
    renewal-percent-threshold: 0.85
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
