management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: 'always'
    beans:
      enabled: true
    info:
      enabled: true
    shutdown:
      enabled: true
  server:
    address: 'localhost'
    port: 11001

spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: 'none'
      naming:
        physical-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        use_sql_comments: true
    show-sql: true
    open-in-view: false
  datasource:
    driver-class-name: 'org.mariadb.jdbc.Driver'
    username: 'web_user'
    password: '1234'
    url: 'jdbc:mariadb://localhost:3306/myDB'
  application:
    name: 'USER-SERVICE'
  boot:
    admin:
      client: # Spring Boot Actuator Admin UI Server
        url: 'http://localhost:15000'
jwt:
  token:
    creator: 'asdf'
    refresh:
      valid:
        time: 3000
      name: 'jwtRefreshToken'
    access:
      valid:
        time: 300
      name: 'jwtAccessToken'
  secret:
    key: '12345678123456781234567812345678123456781234'
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
server:
  port: 11000
api:
  gateway: 'localhost:13000'
